# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TikoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
