# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TikoApp', '0002_auto_20180322_1915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['Event_date']},
        ),
    ]
