# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TikoApp', '0004_auto_20180322_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.PositiveIntegerField(default=254720000000, max_length=13),
        ),
    ]
